name: CI tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: template
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cookiecutter
    - name: Test build
      run: |
        cookiecutter ./template \
          --overwrite-if-exists \
          --default-config \
          --no-input
        cd $(cat ./template/cookiecutter.json | jq -r ".project_name")
        ls -alh
